name: Halo CE ARM64 Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout build files
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Build and analyze Halo CE
        run: sudo -E bash ./build.sh
